### ISSUE TITLE
Spelling mistake in the payment page

### ISSUE THREAD

**Issue by Mocktic** [aayushjain7/Amazon-Clone#3]
On the payment page, the spelling of Delivery in 'Delivery Address' is incorrect it's written "Dilivery Address" which should be changed to "Delivery Address". Though it's something minor and it's just a clone but it's still noticeable. The rest of everything is just awesome.

Here is the error page URL and Screenshot - https://amazo-nclone7.web.app/payment

<img width="562" alt="Capture" src="https://user-images.githubusercontent.com/76685140/127555986-8764e76f-b883-4094-b5a1-00f38b310e77.PNG">

**Comment by aayushjainx** [comment]
Thanks for letting me know! Will correct it surely! 💯
